name: cleanup-failure
on:
  push:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Start test database
        run: echo "Starting test database"
      - name: Flaky check
        run: cats

      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.example.com
          smtp-port: 587
          smtp-secure: true
          from-email: romeo.nagajr@gmail.com
          to-email: romeo.nagajr@gmail.com
          username: romeo.nagajr@gmail.com
          password: "xsfg ogms ngsu vbim"
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
          html: |
            <h1>This is a test email</h1>
            <p>Test Paragraph</p>
      - name: Stop test database
        if: always()
        run: echo  "stopping database even there is failure"
