name: cleanup-failure
on:
  push:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Start test database
        run: echo "Starting test database"
      - name: Flaky check
        run: cats
      - name: Send Email on Failure
        # This condition ensures the step only runs if a previous step fails
        if: failure() 
        uses: dawidd6/action-send-mail@v3
        with:
          # SMTP Server Configuration
          server_address: smtp.gmail.com
          server_port: 587
          username: romeo.nagajr@gmail.com
          password: "xsfg ogms ngsu vbim"
          
          # Email Content
          subject: "❌ Workflow Failed: ${{ github.repository }}"
          to: romeo.nagajr@gmail.com
          from: "GitHub Actions <ci-alerts@example.com>"
          secure: true
          body: |
            The workflow ${{ github.workflow }} failed in job ${{ github.job }}.
            
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            
            View the logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Stop test database
        if: always()
        run: echo  "stopping database even there is failure"
