name: region repository variable
on:
  workflow_dispatch:
jobs:
  region:
    runs-on: ubuntu-latest
    steps:
      - name: echo containing vars context
        run: echo "${{  vars.DEPLOY_REGION  }}"



