name: build_report
on:
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: create a report file
        run: echo date > report.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: report.txt
          retention-days: 5

