name: secret
on:
  push:
jobs:
  secrecy:
    runs-on: ubuntu-latest
    steps:
      - name: get secret
        env:
          APP_TOKEN: "${{  secrets.APP_TOKEN  }}"
        run: |
          if [ -n "$APP_TOKEN" ] ; then
            echo "token is available to this step"
          fi
          

