name: guardrails
on:
  push:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: count files
        run: ls | wc -l

      - name: add readme.md
        run: |
          echo "![ci](https://github.com/miyoming/actions-journey/actions/workflows/tidy.yml/badge.svg)" >> README.md


      - name: Commit and Push Changes
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "romeo.naga]"
          git config --global user.email "romeo.nagajr@gmail.com"

          git add README.md
          # Only commit if there are actual changes to prevent workflow errors
          git diff-index --quiet HEAD || git commit -m "docs: auto-update README.md"
          git push
