name: guardrails
on:
  push:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tidy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: count files
        run: ls | wc -l


      - name: Generate a text file
        run: |
          echo "This file was created by GitHub Actions on $(date)" > dynamic-report.txt

      # 4. Use the Marketplace action to commit and push
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automated: updated dynamic-report.txt"
          file_pattern: 'dynamic-report.txt' # Optional: pushes only this file (defaults to all changes)